variables:
  DOCKER_DRIVER: overlay2
  WORKDIR: hexagon
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: "fast"

stages:
  - build
  - test
  - deploy

image: node:16-slim

Build:
  stage: build
  cache:
    - key: $CI_COMMIT_REF_SLUG-yarn.lock
      paths:
        - node_modules
      policy: pull-push
    - key: $CI_COMMIT_REF_SLUG-contracts
      paths:
        - .yarn
        - artifacts
        - artifacts-zk
        - typechain-types
      policy: pull-push
    - key: $CI_COMMIT_REF_SLUG-client-yarn.lock
      paths:
        - client/node_modules
      policy: pull-push

    - key: $CI_COMMIT_REF_SLUG-client
      paths:
        - client/.yarn
      policy: pull-push
  script:
    - apt-get update && apt-get install -y --no-install-recommends git --reinstall ca-certificates
    - yarn install --non-interactive --cache-folder .yarn
    - yarn compile
    - cd client
    - yarn install --non-interactive --cache-folder .yarn

Contracts unit tests:
  stage: test
  cache:
    - key: $CI_COMMIT_REF_SLUG-yarn.lock
      paths:
        - node_modules
      policy: pull
    - key: $CI_COMMIT_REF_SLUG-contracts
      paths:
        - .yarn
        - artifacts
        - typechain-types
      policy: pull
  script:
    - yarn test

Client unit tests:
  stage: test
  cache:
    - key: $CI_COMMIT_REF_SLUG-client-yarn.lock
      paths:
        - client/node_modules
      policy: pull
    - key: $CI_COMMIT_REF_SLUG-client
      paths:
        - client/.yarn
      policy: pull
  script:
    - cd client
    - yarn test

Contracts deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
  cache:
    - key: $CI_COMMIT_REF_SLUG-yarn.lock
      paths:
        - node_modules
      policy: pull
    - key: $CI_COMMIT_REF_SLUG-contracts
      paths:
        - .yarn
        - artifacts
        - artifacts-zk
        - typechain-types
      policy: pull
  script:
    - yarn deploy:goerli
    - yarn deploy:zksync

pages:
  stage: deploy
  cache:
  - key: $CI_COMMIT_REF_SLUG-contracts
    paths:
      - typechain-types
    policy: pull
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
  script:
    - cd client
    - yarn install --non-interactive
    - yarn build
    - cd ..
    - mv client/dist public
  artifacts:
    paths:
      - public
