arrowParens: avoid
bracketSpacing: true
endOfLine: lf
jsxBracketSameLine: false
printWidth: 100
proseWrap: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all

overrides:
  - files: "*.sol"
    options:
      printWidth: 80
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: false
