# Image used with local docker-compose for development purposes only
#
# Maintainer:
#   Łukasz Kujawski
version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: octant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
