apiVersion: v1
kind: Namespace
metadata:
  name: $DEPLOYMENT_ID
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $DEPLOYMENT_ID
  namespace: argocd
spec:
  project: octant
  destination:
    name: in-cluster
    namespace: $DEPLOYMENT_ID
  sources:
  - repoURL: 'https://gitlab.com/api/v4/projects/48137258/packages/helm/devel'
    targetRevision: 0.2.7
    chart: octant
    helm:
      parameters:
        # From gitlab-ci.yml
        - name: "image.tag"
          value: "$IMAGE_TAG"
        # From CI/CD vars
        - name: "secureIngress"
          value: "$SECURE_INGRESS"
        ## Client
        - name: "webClient.alchemyId"
          value: "$VITE_ALCHEMY_ID"
        ## Backend
        - name: "backendServer.epoch0End"
          value: "$EPOCH_0_END"
        - name: "backendServer.epoch1End"
          value: "$EPOCH_1_END"
        - name: "backendServer.schedulerEnabled"
          value: "$SCHEDULER_ENABLED"
        - name: "backendServer.vaultConfirmWithdrawals"
          value: "$VAULT_CONFIRM_WITHDRAWALS_ENABLED"
        - name: "backendServer.glmClaim.senderNonce"
          value: "$GLM_SENDER_NONCE"
        - name: "backendServer.glmClaim.enabled"
          value: "$GLM_CLAIM_ENABLED"
        - name: "backendServer.snapshotter.enabled"
          value: "$SNAPSHOTTER_ENABLED"
        # Hardcoded in this file
        - name: "ingress.tlsToReplicate.enable"
          value: "true"
        # From Deploy contracts job
        - name: contracts.addresses.startBlock
          value: "$BLOCK_NUMBER"
        - name: contracts.addresses.auth
          value: "$AUTH_CONTRACT_ADDRESS"
        - name: contracts.addresses.deposits
          value: "$DEPOSITS_CONTRACT_ADDRESS"
        - name: contracts.addresses.epochs
          value: "$EPOCHS_CONTRACT_ADDRESS"
        - name: contracts.addresses.proposals
          value: "$PROPOSALS_CONTRACT_ADDRESS"
        - name: contracts.addresses.vault
          value: "$VAULT_CONTRACT_ADDRESS"
        - name: contracts.addresses.withdrawals_target
          value: "$WITHDRAWALS_TARGET_CONTRACT_ADDRESS"
        - name: contracts.addresses.glm
          value: "$GLM_CONTRACT_ADDRESS"
        - name: contracts.addresses.gnt
          value: "$GNT_CONTRACT_ADDRESS"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: "batch"
    kind: "Job"
    jsonPointers:
    - /metadata/annotations
    - /spec/template/metadata
    - /spec/template/labels
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data

