apiVersion: v1
kind: Namespace
metadata:
  name: $DEPLOYMENT_ID
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $DEPLOYMENT_ID
  namespace: argocd
spec:
  project: octant
  destination:
    name: in-cluster
    namespace: $DEPLOYMENT_ID
  sources:
  # https://linear.app/golemfoundation/issue/CAQD-142/move-helm-git-repository-to-devops-space
  - repoURL: 'https://git.ring0.cc/mike/helm/raw/branch/master'
    targetRevision: 0.2.4
    chart: octant
    helm:
      parameters:
        # From gitlab-ci.yml
        - name: "image.tag"
          value: "$IMAGE_TAG"
        # From CI/CD vars
        - name: "secureIngress"
          value: "$SECURE_INGRESS"
        - name: "contracts.deploy"
          value: "false"
        - name: "contracts.epochDuration"
          value: "$EPOCH_DURATION"
        - name: "contracts.decisionWindow"
          value: "$DECISION_WINDOW"
        - name: "backendServer.epoch0End"
          value: "$EPOCH_0_END"
        - name: "backendServer.epoch1End"
          value: "$EPOCH_1_END"
        # Hardcoded in this file
        - name: "contracts.addresses.multisigAddress"
          value: "$MULTISIG_ADDRESS"
        - name: "backendServer.schedulerEnabled"
          value: "True"
        # From Deploy contracts job
        - name: contracts.addresses.startBlock
          value: "$BLOCK_NUMBER"
        - name: contracts.addresses.auth
          value: "$AUTH_CONTRACT_ADDRESS"
        - name: contracts.addresses.deposits
          value: "$DEPOSITS_CONTRACT_ADDRESS"
        - name: contracts.addresses.epochs
          value: "$EPOCHS_CONTRACT_ADDRESS"
        - name: contracts.addresses.proposals
          value: "$PROPOSALS_CONTRACT_ADDRESS"
        - name: contracts.addresses.vault
          value: "$VAULT_CONTRACT_ADDRESS"
        - name: contracts.addresses.withdrawals_target
          value: "$WITHDRAWALS_TARGET_CONTRACT_ADDRESS"
        - name: contracts.addresses.glm
          value: "$GLM_CONTRACT_ADDRESS"
        - name: contracts.addresses.gnt
          value: "$GNT_CONTRACT_ADDRESS"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: "batch"
    kind: "Job"
    jsonPointers:
    - /metadata/annotations
    - /spec/template/metadata
    - /spec/template/labels
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data

