apiVersion: v1
kind: Namespace
metadata:
  name: $DEPLOYMENT_ID
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $DEPLOYMENT_ID
  namespace: argocd
spec:
  project: octant
  destination:
    name: in-cluster
    namespace: $DEPLOYMENT_ID
  sources:
  # https://linear.app/golemfoundation/issue/CAQD-142/move-helm-git-repository-to-devops-space
  - repoURL: 'https://git.ring0.cc/mike/helm/raw/branch/master'
    targetRevision: 0.1.91
    chart: octant
    helm:
      parameters:
        # From gitlab-ci.yml
        - name: "image.tag"
          value: "$IMAGE_TAG"
        # From CI/CD vars
        - name: "secureIngress"
          value: "$SECURE_INGRESS"
        - name: "contracts.deploy"
          value: "$DEPLOY_CONTRACTS"
        - name: "contracts.epochDuration"
          value: "$EPOCH_DURATION"
        - name: "contracts.decisionWindow"
          value: "$DECISION_WINDOW"
        # Hardcoded in this file
        - name: "contracts.addresses.multisigAddress"
          value: "0xfC9527820A76b515a2c66C22e0575501DEDD8281"
        - name: "contracts.addresses.allocations"
          value: "0x0000000000000000000000000000000000000000"
        - name: "backendServer.schedulerEnabled"
          value: "True"
        - name: "backendServer.vaultConfirmWithdrawals"
          value: "True"
        - name: "backendServer.epoch0End"
          value: "$EPOCH_0_END"
        - name: "backendServer.epoch1End"
          value: "$EPOCH_1_END"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: "batch"
    kind: "Job"
    jsonPointers:
    - /metadata/annotations
    - /spec/template/metadata
    - /spec/template/labels
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data

