version: '3'
services:
  graph-node:
    network_mode: "host"
    image: graphprotocol/graph-node:v0.26.0
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: localhost
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'localhost:5001'
      ethereum: ${NETWORK_NAME}:${RPC_PROVIDER}
      GRAPH_LOG: info
  ipfs:
    network_mode: "host"
    image: ipfs/go-ipfs:v0.10.0
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    network_mode: "host"
    image: postgres
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/data/postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
